# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 09:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('architect', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('engineer', models.CharField(blank=True, max_length=250, null=True)),
                ('designer', models.CharField(blank=True, max_length=250, null=True)),
                ('project_year', models.DateTimeField(auto_now_add=True)),
                ('site_area', models.CharField(blank=True, max_length=250, null=True)),
                ('cover', models.ImageField(upload_to='zoom_cover')),
                ('pictures', models.FileField(upload_to='zoom_pictures')),
                ('content_fr', models.TextField()),
                ('content_en', models.TextField()),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('published', 'published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoom_zooms', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
    ]
