# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0002_zoom_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoom',
            name='project_year',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
