# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 08:28
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presta', '0002_prestataire_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestataire',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
