# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presta', '0004_auto_20180608_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestataire',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presta_ville', to='presta.Ville'),
        ),
    ]
