# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presta', '0006_auto_20180608_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestataire',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
