# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presta', '0008_prestataire_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestataire',
            name='site',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
