# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(default=1, upload_to='cover'),
            preserve_default=False,
        ),
    ]
